language: rust
cache: cargo

rust:
  - stable

matrix:
  fast_finish: true
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
      script:
        - cd frida-gum-sys && wget https://github.com/frida/frida/releases/download/12.11.12/frida-gum-devkit-12.11.12-linux-x86_64.tar.xz -O frida-gum.tar.xz && tar xJvf frida-gum.tar.xz
        - cargo fmt -- --check
        - cargo clippy --all-features -- -D warnings

script: |
  cd frida-gum-sys && wget https://github.com/frida/frida/releases/download/12.11.12/frida-gum-devkit-12.11.12-linux-x86_64.tar.xz -O frida-gum.tar.xz && tar xJvf frida-gum.tar.xz &&
  cargo build --verbose &&
  cargo test  --verbose &&
  cargo doc   --verbose

branches:
  only:
    - staging
    - trying
    - master