language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
      script:
        - cargo fmt    -- --check
        - cargo clippy -- -D clippy

script: |
  cargo build --verbose &&
  cargo test  --verbose &&
  cargo doc   --verbose

branches:
  only:
    - staging
    - trying
    - master