[package]
name = "frida-gum-sys"
version = "0.1.0"
authors = ["meme <keegan@sdf.org>"]
edition = "2018"

[features]
event-sink = ["cc"]

[build-dependencies]
bindgen = "0.53.1"
cc = { version = "1.0", optional = true }