[package]
name = "frida-gum"
version = "0.1.0"
authors = ["meme <keegan@sdf.org>"]
edition = "2018"

[features]
event-sink = ["frida-gum-sys/event-sink"]

[dependencies]
frida-gum-sys = { path = "../frida-gum-sys" }
num = "0.2"
num-derive = "0.3"
num-traits = "0.2"
paste = "1"

[badges]
travis-ci = { repository = "meme/frida-rust", branch = "master" }
maintenance = { status = "actively-developed" }