[package]
name = "frida-gum"
version = "0.1.0"
authors = ["meme <keegan@sdf.org>"]
edition = "2018"

[dependencies]
frida-gum-sys = { path = "../frida-gum-sys" }
num = "0.2"
num-derive = "0.3"
num-traits = "0.2"

