[package]
name = "hello"
version = "0.1.0"
authors = ["meme <keegan@sdf.org>"]
edition = "2018"
license = "wxWindows"
publish = false

[dependencies]
frida = { path = "../../../frida" }
frida-sys = { path = "../../../frida-sys" }
lazy_static = "1.4"
